[package]
name = "lita-tokenizers-kytea-py"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[lib]
name = "lita_tokenizers_kytea_py"
crate-type = ["cdylib"]

[dependencies]
pyo3.workspace = true

kytea-sys.workspace = true
tokenizers-core.workspace = true
