[project]
name = "lita-tokenizers-kytea-py"
version = "0.1.0"
description = "KyTea bindings for Python."
readme = "README.md"
requires-python = ">=3.11"

classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]

dependencies = []

[build-system]
requires = ["maturin>=1.15.0,<2"]
build-backend = "maturin"

[tool.maturin]
python-source = "python"
