[package]
name = "lita-tokenizers-kytea-js"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[lib]
name = "lita_tokenizers_kytea_js"
crate-type = ["cdylib"]

[dependencies]
napi = { workspace = true, features = ["napi4"] }
napi-derive.workspace = true

kytea-sys.workspace = true
tokenizers-core.workspace = true

[build-dependencies]
napi-build.workspace = true
