/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export declare class FileStream {
  constructor(path: string, mode: string)
  flush(): void
}

export declare class KyTea {
  constructor()
  readModel(path: string): void
  readModelFromBytes(bytes: Buffer, format: string): void
  tokenize(input: Stream, output: Stream): void
}

export declare class StringStream {
  constructor(string?: string | undefined | null)
  asStr(): string
}

export type Stream = StringStream | FileStream
