[package]
name = "kytea-sys"
version = "0.2.2"

description = "FFI binding and safe wrappers of KyTea"

exclude = ["kytea-src/data/model.bin.gz"]

edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]

[dev-dependencies]
tempfile = "3"

[build-dependencies]
cc = { version = "1.2", features = ["parallel"] }
